resources:
  containers:
  - container: buildbase
    image: 'iwillspeak/ullage-linux-build-base'
    options: '-m 4G'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      LLVM9:
        llvm_tag: 'llvm\@9'
        features: 'llvm-9'
        llvm_ver: '90'
      LLVM10:
        llvm_tag: 'llvm'
        features: 'llvm-10'
        llvm_ver: '100'
  steps:
    - script: 'brew install $(llvm_tag)'
      displayName: Brew install LLVM
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: |
        export PATH=/usr/local/bin:$PATH             # Local bin (brew)
        source ~/.cargo/env
        export LLVM_SYS_$(llvm_ver)_PREFIX=/usr/local/opt/$(llvm_tag)
        export LLVM_CONFIG_PATH=${LLVM_SYS_$(llvm_ver)_PREFIX}/bin/llvm-config
        cargo install just
        ./build.sh features=$(features) test
      displayName: './build.sh test'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  container: buildbase
  steps:
    - script: |
        python3 --version
        export PATH=${PATH}:~/.local/bin/
      displayName: Python
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: |
        source ~/.cargo/env
        export PATH=${PATH}:~/.local/bin/:/usr/lib/llvm-9/bin
        export LLVM_SYS_90_PREFIX=/usr/lib/llvm-9
        export LLVM_CONFIG_PATH=${LLVM_SYS_90_PREFIX}/bin/llvm-config
        cargo install just
        ./build.sh test
      displayName: './build.sh test'
