jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - script: 'brew install llvm'
      displayName: Brew install LLVM
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: |
        export PATH=/usr/local/bin:$PATH             # Local bin (brew)
        source ~/.cargo/env
        export LLVM_SYS_80_PREFIX=/usr/local/opt/llvm
        pip3 install virtualenv
        ./build.sh test
      displayName: './build.sh test'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  container: 'ubuntu:bionic'
  steps:
    - script: |
        lscpu
        free -h
        who am i
        su root
        who am i
      displayName: Dump Box Configuration
    - script: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-virtualenv
        python3 --version
      displayName: Install Python3
    - script: |
        apt-get install -y gcc binutils
        gcc --version
        ld --version
      displayName: Install latest gcc
    - script: |
        cat > llvm.list <<EOF
        # 8
        deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main
        deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main
        EOF
        cp llvm.list /etc/apt/sources.list.d/
        apt-get update
        apt-get install -y llvm-8-dev zlib1g-dev libterminfo-dev
      displayName: Install LLVM
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: |
        source ~/.cargo/env
        export LLVM_SYS_80_PREFIX=/usr/lib/llvm-8
        ./build.sh test
      displayName: './build.sh test'
