pool:
  vmImage: 'ubuntu-16.04'
container: 'rust:latest'
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: 'pip3 install virtualenv'
  - script: './build.sh test'
    displayName: './build.sh test'
