pool:
  vmImage: 'ubuntu-16.04'

trigger:
  paths:
    include: 
      - '.ci'

variables:
  dockerId: iwlllspeak
  imageName: ullage-linux-build-base

env:
  pswd: $(dockerPassword)

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  workingDirectory: '.ci'
